FROM debian:jessie-slim
ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb http://archive.debian.org/debian/ jessie main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update -y && \
    apt-get install -y curl ca-certificates build-essential libsystemd-dev cmake make bash sudo wget unzip dh-make flex bison && \
    apt-get install -y --reinstall lsb-base lsb-release && \
    apt-get -t jessie-backports install -y cmake
