FROM debian:jessie-slim
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \
    apt-get install -y -qq curl ca-certificates build-essential libsystemd-dev cmake make bash sudo wget unzip dh-make && \
    apt-get install -y -qq --reinstall lsb-base lsb-release && \
    echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get -t jessie-backports install -y cmake
