FROM amazonlinux:1

RUN yum -y update && \
    yum install -y rpm-build curl ca-certificates gcc gcc-c++ cmake make bash wget unzip systemd-devel wget flex cmake3 && \
    cd /tmp && \
    wget http://ftp.gnu.org/gnu/bison/bison-3.4.tar.gz && \
    tar xvzf bison-3.4.tar.gz && \
    cd bison-3.4 && \
    ./configure && \
    make install

# td-agent-bit checks for the presense of /usr/share/upstart to install upstart conifg
RUN mkdir /usr/share/upstart
