FROM arm64v8/debian:stretch
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \
    apt-get install -y -qq curl ca-certificates build-essential \
                           cmake make bash sudo wget unzip dh-make \
                           libsystemd-dev zlib1g-dev flex bison && \
    apt-get install -y -qq --reinstall lsb-base lsb-release
