FROM resin/rpi-raspbian:stretch
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \
    apt-get install -y -qq curl ca-certificates build-essential libsystemd-dev cmake make bash sudo wget unzip nano vim dh-make fakeroot && \
    apt-get install -y -qq --reinstall lsb-base lsb-release
